scriptencoding utf-8

set nocompatible
set bs=2                " Allow backspacing over everything in insert mode
set ai                  " Always set auto-indenting on
set history=500          " keep 50 lines of command history
set ruler

set softtabstop=2
set expandtab
set tabstop=2           " Control the number of space characters
set shiftwidth=2        " Change the number of space characters

set incsearch           " To move the search while typing
set laststatus=2
set cmdheight=1
set backspace=2
syn on
set rnu                 " Relative lines numbers
set number              " Current line number
set mouse=a

set ignorecase
set smartcase
set hlsearch

" Only one space when joining lines
set nojoinspaces

set undofile

" Wild menu (completion)
set wildmenu
set wildmode=full
"set wildmode=longest,list

" enable folding
set foldenable

" Color the 80th column
" set colorcolumn=80

set matchpairs+=<:>

set showcmd

set cursorline
set cursorcolumn

set hidden

let mapleader = ","

set list
set listchars=nbsp:¤,tab:->,trail:·,extends:>,precedes:<

call plug#begin('~/.nvim/plugged')

Plug 'benekastah/neomake'

Plug 'derekwyatt/vim-scala'

" Plug 'scrooloose/syntastic'

Plug 'airblade/vim-gitgutter'
Plug 'flazz/vim-colorschemes'
Plug 'kien/ctrlp.vim'
Plug 'gre/play2vim'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/vim-peekaboo'
Plug 'bling/vim-airline'

" call unite#custom#profile( 'source/reddit, source/wikipedia', 'context', { 'keep_focus' : 1, 'no_quit' : 1 })


call plug#end()

colorscheme molokai

let mapleader = ","

nmap gh <Plug>GitGutterNextHunk
nmap gH <Plug>GitGutterPrevHunk

map <leader>r :NERDTreeFind<cr>


let g:ctrlp_match_window = 'bottom,order:btt,min:1,max:50,results:50'
let g:ctrlp_working_path_mode = ''
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore-dir=.git
      \ --ignore-dir=.svn
      \ --ignore-dir=.hg
      \ --ignore-dir=target
      \ --ignore=*.un~
      \ --ignore=*.swo
      \ --ignore=*.swp
      \ --ignore-dir=.DS_Store
      \ --ignore=*.class
      \ --ignore-dir=bower_components
      \ --ignore-dir=vendors
      \ -g ""'


map <C-j> :bnext<cr>
map <C-k> :bprevious<cr>

map Y y$

" nnoremap ; :

au BufRead,BufNewFile *.jad setfiletype java

inoremap jk <esc>


autocmd! BufWritePost * Neomake
